#! /bin/sh

bin=$IRSTLM/bin

testdir=$1
cd $testdir

inputfile="gunzip -c input.gz"
outputfile=output

$bin/plsa -te="$inputfile" -m=model -t=30 -it=20 -tf=$outputfile  > /dev/null 2>&1 
cat $outputfile | perl -pe 's/[\t ]+/\n/g;'

rm $outputfile
