#! /bin/sh

bin=$IRSTLM/bin

testdir=$1
cd $testdir

for pruning in "-p" "" ; do 
for smoothing in "witten-bell" "shift-beta" "improved-shift-beta" "stupid-backoff" ; do 
for subdict in "-d subdict" "" ; do
$bin/build-lm.sh  -i 'gunzip -c input.gz' -n 4 -o output1.gz -k 5 $pruning -s $smoothing $subdict > /dev/null 2>&1
$bin/build-lm.sh  -i 'gunzip -c input.gz' -n 4 -o output2.gz -k 1 $pruning -s $smoothing $subdict > /dev/null 2>&1

gunzip output1.gz output2.gz
diff output1 output2
rm output1 output2

done
done
done
