#! /bin/sh

bin=$IRSTLM/bin

testdir=$1
cd $testdir

inputfile=input.gz
outputfile=output.gz

$bin/quantize-lm $inputfile - /tmp/ppp | gzip -c > $outputfile
gunzip -c $outputfile | perl -pe 's/[\t ]+/\n/g;'

rm $outputfile

