#! /bin/sh

bin=$IRSTLM/bin

testdir=$1
cd $testdir

inputfile=input.gz
outputfile=output_$$.gz

for pruning in "-p" ; do 
for smoothing in "witten-bell" "shift-beta" "improved-shift-beta" "stupid-backoff" ; do 
$bin/build-lm.sh  -i "gunzip -c $inputfile" -n 4 -o $outputfile -k 5 $pruning -s $smoothing > /dev/null 2>&1

gunzip -c $outputfile | perl -pe 's/[\t ]+/\n/g'
rm $outputfile

done
done
